### ISSUE TITLE
Redaxo abgeschossen :(

### ISSUE THREAD

**Issue by dpf-dd** [tbaddade/redaxo_sherlock#11]
Hallo Gregor,

habe den Sherlock soeben auf einem (fast) jungfräulichen Redaxo 4.6.2. installiert (PHP 5.5.x)...
Jetzt bekomme ich im Frontend UND Backend eine weiße Seite und folgenden Fehlercode im Error-Log:

[Mon Nov 16 08:18:05.949565 2015] [fcgid:warn] [pid 4959] [client 185.38.51.139:8521] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare class rex_socket in /var/www/clients/client0/web2/web/redaxo/include/addons/sherlock/vendor/redaxo5/lib/util/socket/socket.php on line 22

Need Help -.-

**Comment by tbaddade** [comment]
Die socket Class ist bei redaxo jetzt ständig dabei. Das war damals noch nicht so. Heißt kurz um, dass einfach die Class nicht ein zweitesmal required werden darf.
