### ISSUE TITLE
Fehlermeldung nach Upload auf Server ...

### ISSUE THREAD

**Issue by royalemotions** [tbaddade/redaxo_sherlock#12]
Parse error: syntax error, unexpected '[' in /kunden/161233_73110/rp-hosting/87006/87006/dev-redaxo5/redaxo/src/core/boot.php on line 24

> Das kommt nach Upload

Ist da was falsch eingspielt worden??

**Comment by royalemotions** [comment]
Ich bin quasi ein DOW für die Installation ;) Also bitte mal gucken oder TIPP geben. DANKE!

**Comment by tbaddade** [comment]
Der Fehler kommt nicht vom Addon, welches nebenbei gar nicht für Redaxo 5 ist sonder für Redaxo 4.
Ich vermute das deine Php Version nicht ausreicht. Nimm zur Installation für Redaxo 5 die Beta die zum Download bereit steht.
